### PR TITLE
Add AVAX Token

### PR DESCRIPTION
**Pull request by jaguard2021**
Action: add / update / remove token (keep those that applies)
Context / rational:

PR checklist:
- [x] I've kept the token list in alphabetical order based on token symbol
- [x] I've updated the `updatedAt` (and potentially `createdAt`) fields
- [x] I've update the list version number as per README instruction

### CODE REVIEW

**Review by cipoto — APPROVED** [review]
PR checklist: is done

**Comment by phoax** [comment]
> PR checklist: is done

Hello, 
why is it Matic on https://lineascan.build/address/0x265b25e22bcd7f10a5bd6e6410f10537cc7567e8
image

Also the contract is not verified.

**Comment by phoax** [comment]
> PR checklist: is done

Hello, could you please :
- verify the contract please
- change updatedAt
- update the list version

**Comment by jaguard2021** [comment]
Thanks @phoax @cipoto ,

**Comment by cipoto** [comment]
> > PR checklist: is done
> 
> Hello, could you please :
> 
> * verify the contract
> * change updatedAt
> * update the list version

I have checked the contract, and there is nothing wrong and to this day the contract is still functioning and being used by users on the Linea Goerlic network. Thank You

**Comment by arthur-remy** [comment]
What @phoax was asking is that the contract must be verified on Etherscan.
Also I see you indicated that the token is native to Linea which is not the case. What is the bridge used with this token?

**Comment by arthur-remy** [comment]
Hey @jaguard2021 @cipoto,
We are still waiting for your response here. Please let us know by Jan 19 otherwise we will close the PR

**Pull request closed without merging**
